CREATE TABLE donations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(10) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    item_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 